name: Unpake_payload
on: push
jobs:
  Unpack:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      run: |
        sudo apt-get update
        sudo apt-get -y install git python3 python3-pip axel
    - name: Clone source code
      run: |
        git clone https://github.com/vm03/payload_dumper.git payload
        git clone https://github.com/liujixings/payload_unpack_action.git link
        cp ./link/link ./payload/link
        cd payload
        pip3 install -r requirements.txt
        axel -q -o miui.zip -n 64 `cat ./link`
    - name: Unpak miui
      run: |
        cd payload
        unzip miui.zip
        rm -rf miui.zip
    - name: Unpak payload
      run: |
        cd payload
        python3 payload_dumper.py payload.bin boot.img
        rm -rf payload.bin
    - name: View
      run: |
       ls payload
       ls payload/output
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: boot
        path: payload/output/boot.img
